
CC		= gcc
CFLAGS	= -g
LDLIBS	=
LIB		= libT++.so

EXE		= testload
OBJS	= main.o 

$(EXE): $(OBJS) lib/$(LIB)
	$(CC) $(CFLAGS) -Llib -rdynamic -o $(EXE) $(OBJS) $(LDLIBS)

lib/$(LIB):
	cd lib ; make -f Makefile.BSD $(LIB)

clean:
	- rm -f $(EXE)
	- rm -f $(OBJS)
	( cd lib ; make -f Makefile.BSD clean )

