#!/bin/sh

# A for loop operates by iterating over
# list of values separated by spaces.  Note
# that is doesn't matter how many spaces
# we use to separate things
for i in 0 1 2	4   8 16
do
	echo "Loop variable is now '${i}'"
done

echo " . . . Done first for loop"

for value in hi there	how   "are   you?"
do
	echo "Loop variable is now '${value}'"
done
