
CFLAGS	= -g
LDLIBS	=
LIB		= libTdarwin.so

EXE		= testloadDarwin
OBJS	= main-Darwin.o 

$(EXE): $(OBJS) lib/$(LIB)
	$(CC) $(CFLAGS) -Llib -rdynamic -o $(EXE) $(OBJS) $(LDLIBS)

lib/$(LIB):
	cd lib ; make -f Makefile.Darwin $(LIB)

clean:
	- rm -f $(EXE)
	- rm -f $(OBJS)
	( cd lib ; make -f Makefile.Darwin clean )

